site_name: BBKB Community
site_url: https://bbkb-community.github.io
site_description: A gallery of pocket-sized keyboards and computers built using leftover stock of BB keyboards.
theme:
  name: material
  custom_dir: overrides
  logo: images/bbkb_logo.svg
  favicon: images/bbkb_logo.svg
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - toc.integrate
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: orange
    - scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: orange
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
  - pymdownx.snippets:
      base_path: includes/snippets
watch:
  - includes
plugins:
  - social
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bbkb-community/bbkb-community.github.io
nav:
  - Welcome: index.md
  - Computers:
    - computers/index.md
    - HackberryPi by Zitao: computers/hackberrypi.md
    - Colorberry by Alex: computers/colorberry.md
    - T-Deck by LILYGO: computers/t-deck.md
    - Beepis by HackMods: computers/beepis.md
  - Keyboards:
    - keyboards/index.md
    - BB Keyboards by Zitao: keyboards/bb_keyboards_zitao.md
    - T-Keyboard by LILYGO: keyboards/t-keyboard.md
  - Inactive Projects:
    - inactive-projects/index.md
    - Beepy by SQFMI: inactive-projects/beepy.md
    - BBQ20KBD by Solder Party: inactive-projects/bbq20kbd.md
