site_name: BBKB Community
site_url: https://bbkb-community.org
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: bbkb/logo
  favicon: images/bbkb_logo.svg
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - toc.integrate
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: orange
    - scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: orange
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
nav:
  - Welcome: index.md
  - Computers: computers/index.md
  - Keyboards: keyboards/index.md
  - Inactive Projects: inactive-projects/index.md
