[project]
name = "bbkb-community"
version = "0.1.0"
description = "Website documenting hardware using BB keyboards"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material[imaging]>=9.5.48",
]
